### ISSUE TITLE
Convoy scape

### ISSUE THREAD

**Issue by ghost** [noskillsben/givesendgo_donation_scraper#1]
Is there any way to add the location data of where the donation was made from?

**Comment by noskillsben** [comment]
On this Github, only the public data scraped will be posted but you can check out this observable hq link for my location analysis using comment and names + state/province and country based on the leak last weekend. canadas-freedom-convoy-2022-donation-data. I'll add some extra graph showing just how inaccurate my analysis was this weekend :. (

I might add the data from the latest leak that included the adopt a trucker data but that leak includes internal Givesendgo code and a lot more and I don't really want to download it.

I would suggest getting the comments from this Github and merging them with the leak data if you want emoji data. Otherwise the leak data has this plus more.

**Comment by noskillsben** [comment]
sorry, I just noticed I did not post the full observablehq address. 
- https://observablehq.com/@5e9ee33b437339a5/canadas-freedom-convoy-2022-donation-data
I Just saw givesendgo is back up and accepting donations. I'm going to split the convoy data into another github repository and keep the scraper here for use in future unrelated givesendgo campaigns.
